server:
  port: 9082
  
jwtUrl: 
   https://oauth.insigniaconsultancy.com:8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 364520571875-t3cjtcra85chc1hgniv3ltkb8q1sgcf1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri : https://oauth.insigniaconsultancy.com:8082/login/oauth2/code/google
          facebook :
            clientId: 232153986349819
            clientSecret: 6cfb9fff58384ebfea09a168bf645266 
            redirect-uri : https://oauth.insigniaconsultancy.com:8082/login/oauth2/code/facebook
          github :
            clientId: ea34a428c00bc2508594 
            clientSecret: bac0b33b676e58160efaf4ce0f05b83f1ac0b116 
            redirect-uri : https://oauth.insigniaconsultancy.com:8082/login/oauth2/code/github